server:
  port: ${PORT_ADMIN:8401}

spring:
  security:
    user:
      name: ${ADMIN_SECURITY_USERNAME:zclcs}
      password: ${ADMIN_SECURITY_PASSWORD:123456}

  boot:
    admin:
      ui:
        title: ${spring.application.name}

my:
  log:
    enable-elk: ${LOG_ENABLE_ELK:false}
    enable-log-for-controller: ${LOG_ENABLE_LOG_FOR_CONTROLLER:false}
    logstash-host: ${LOG_LOGSTASH_HOST:127.0.0.1:4560}