server:
  port: ${admin-port:8401}

spring:
  security:
    user:
      name: ${admin-security-username:zclcs}
      password: ${admin-security-password:123456}

  boot:
    admin:
      ui:
        title: ${spring.application.name}

my:
  log:
    enable-elk: ${enable-elk:false}
    enable-log-for-controller: ${enable-log-for-controller:false}
    logstash-host: ${logstash-host:127.0.0.1:4560}