server:
  port: ${admin-port:8401}

spring:
  security:
    user:
      name: ${admin-security-username:zclcs}
      password: ${admin-security-password:123456}

  boot:
    admin:
      ui:
        title: ${spring.application.name}