server:
  port: ${PORT_SERVER_DICT:8205}

spring:
  datasource:
    dynamic:
      primary: primary
      datasource:
        primary:
          driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
          url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/${DB_NAME_DICT:cloud_dict}?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai}
          username: ${DATASOURCE_USERNAME:root}
          password: ${DATASOURCE_PASSWORD:root}

system:
  dict:
    mq-type: none
    text-value-default-null: true
    on-boot-refresh-dict: false
    cache:
      enabled: true
      maximum-size: 500
      initial-capacity: 50
      duration: 30s
      miss-num: 50
    controller:
      enabled: true
      prefix: /cache

mybatis-plus:
  type-aliases-package: com.zclcs.common.core.entity.dict
  mapper-locations: classpath:com/zclcs/server/dict/mapper/*.xml

my:
  cloud:
    security:
      enable: true
      anon-uris: /v2/api-docs,/v2/api-docs-ext
      only-fetch-by-gateway: false