server:
  port: ${PORT_TX_KNIFE4J:8401}

knife4j:
  # 开启聚合组件
  enableAggregation: ${DOC_ENABLE_AGGREGATION:true}
  cloud:
    enable: true
    routes:
      - name: 鉴权服务
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_AUTH:/auth}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: 系统服务
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_SYSTEM:/system}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: 快速开发服务
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_GENERATOR:/generator}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: 测试服务
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_TEST:/test}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: 文件服务
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_MINIO:/minio}/v2/api-docs?group=default
        swaggerVersion: 2.0