server:
  port: ${PORT_KNIFE4J:8401}

spring:
  security:
    user:
      name: ${KNIFE4j_USERNAME:zclcs}
      password: ${KNIFE4j_PASSWORD:123456}

knife4j:
  # 开启聚合组件
  enableAggregation: ${DOC_ENABLE_AGGREGATION:true}
  cloud:
    enable: true
    routes:
      - name: ${SERVICE_NAME_AUTH:auth}
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_AUTH:/auth}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: ${SERVICE_NAME_SERVER_SYSTEM:server-system}
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_SYSTEM:/system}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: ${SERVICE_NAME_SERVER_GENERATOR:server-generator}
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_GENERATOR:/generator}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: ${SERVICE_NAME_SERVER_TEST:server-test}
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_TEST:/test}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: ${SERVICE_NAME_SERVER_MINIO:server-minio}
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_MINIO:/minio}/v2/api-docs?group=default
        swaggerVersion: 2.0
      - name: ${SERVICE_NAME_SERVER_DICT:server-dict}
        uri: ${GATEWAY_HOST:127.0.0.1}:${PORT_GATEWAY:8301}
        location: ${SERVICE_PATH_SERVER_DICT:/dict}/v2/api-docs?group=default
        swaggerVersion: 2.0