server:
  port: ${PORT_GATEWAY:8301}

spring:
  boot:
    admin:
      client:
        url: http://${ADMIN_HOST:127.0.0.1}:${PORT_ADMIN:8401}
        username: ${ADMIN_SECURITY_USERNAME:zclcs}
        password: ${ADMIN_SECURITY_PASSWORD:123456}
        instance:
          prefer-ip: true

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ${SERVICE_NAME_AUTH:auth}
          uri: lb://${SERVICE_NAME_AUTH:auth}
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/${SERVICE_NAME_AUTH:auth}
        - id: ${SERVICE_NAME_SERVER_SYSTEM:server-system}
          uri: lb://${SERVICE_NAME_SERVER_SYSTEM:server-system}
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/${SERVICE_NAME_SERVER_SYSTEM:server-system}
      loadbalancer:
        use404: true
      default-filters:
        - StripPrefix=1
        - MyDocGatewayHeaderFilter

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  # 网关增强配置
  # data:
  #   mongodb:
  #     host: ${mongo.url}
  #     port: 27017
  #     database: cloud_route

  redis:
    database: ${REDIS_GATEWAY_DATABASE:3}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

# 网关增强配置
my:
  gateway:
    enhance: false
    jwt:
      secret: 123456
      expiration: 36000

  doc:
    gateway:
      enable: true
      resources: ${DOC_GATEWAY_RESOURCES:"server-system,auth"}

  log:
    enable-elk: ${LOG_ENABLE_ELK:false}
    enable-log-for-controller: ${LOG_ENABLE_LOG_FOR_CONTROLLER:false}
    logstash-host: ${LOG_LOGSTASH_HOST:127.0.0.1:4560}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    socialfallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eager-load:
    enabled: true

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway

