server:
  port: ${PORT_GATEWAY:8301}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ${SERVICE_NAME_AUTH:auth}
          uri: lb://${SERVICE_NAME_AUTH:auth}
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/${SERVICE_NAME_AUTH:auth}
        - id: ${SERVICE_NAME_SERVER_SYSTEM:server-system}
          uri: lb://${SERVICE_NAME_SERVER_SYSTEM:server-system}
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/${SERVICE_NAME_SERVER_SYSTEM:server-system}
        - id: ${SERVICE_NAME_SERVER_GENERATOR:server-generator}
          uri: lb://${SERVICE_NAME_SERVER_GENERATOR:server-generator}
          predicates:
            - Path=/generator/**
          filters:
            - name: Hystrix
              args:
                name: generatorfallback
                fallbackUri: forward:/fallback/${SERVICE_NAME_SERVER_GENERATOR:server-generator}
        - id: ${SERVICE_NAME_SERVER_TEST:server-test}
          uri: lb://${SERVICE_NAME_SERVER_TEST:server-test}
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/${SERVICE_NAME_SERVER_TEST:server-test}
        - id: ${SERVICE_NAME_SERVER_MINIO:server-minio}
          uri: lb://${SERVICE_NAME_SERVER_MINIO:server-minio}
          predicates:
            - Path=/minio/**
          filters:
            - name: Hystrix
              args:
                name: miniofallback
                fallbackUri: forward:/fallback/${SERVICE_NAME_SERVER_MINIO:server-minio}
      loadbalancer:
        use404: true
      default-filters:
        - StripPrefix=1
        - MyDocGatewayHeaderFilter

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  # 网关增强配置
  # data:
  #   mongodb:
  #     host: ${mongo.url}
  #     port: 27017
  #     database: cloud_route

  redis:
    database: ${REDIS_GATEWAY_DATABASE:3}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

# 网关增强配置
my:
  gateway:
    enhance: false
    jwt:
      secret: 123456
      expiration: 36000

  doc:
    gateway:
      enable: true
      resources: ${DOC_GATEWAY_RESOURCES:auth,server-system,server-generator,server-test}

  log:
    enable-log-for-controller: ${LOG_CONTROLLER_PARAMS:false}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    socialfallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eager-load:
    enabled: true

