version: '3'

services:
  admin:
    image: 192.168.33.10:3000/cloud/admin:latest
    container_name: admin
    networks:
      - web_net
    environment:
      JAVA_TOOL_OPTIONS: "${ADMIN_JAVA_OPS}"
    volumes:
      - ./log/admin:/log/admin
      - ./log/admin/skywalking:/agent/logs
      - ./agent/agent.config:/agent/config/agent.config
    env_file: .env
    ports:
      - "8401:8401"
  gateway:
    image: 192.168.33.10:3000/cloud/gateway:latest
    container_name: gateway
    networks:
      - web_net
    environment:
      JAVA_TOOL_OPTIONS: "${GATEWAY_JAVA_OPS}"
    volumes:
      - ./log/gateway:/log/gateway
      - ./log/gateway/skywalking:/agent/logs
      - ./agent/agent.config:/agent/config/agent.config
    env_file: .env
  auth:
    image: 192.168.33.10:3000/cloud/auth:latest
    container_name: auth
    networks:
      - web_net
    environment:
      JAVA_TOOL_OPTIONS: "${AUTH_JAVA_OPS}"
    volumes:
      - ./log/auth:/log/auth
      - ./log/auth/skywalking:/agent/logs
      - ./agent/agent.config:/agent/config/agent.config
    env_file: .env
  tx-manager:
    image: 192.168.33.10:3000/cloud/tx-manager:latest
    container_name: tx-manager
    networks:
      - web_net
    environment:
      JAVA_TOOL_OPTIONS: "${TX_MANAGER_JAVA_OPS}"
    volumes:
      - ./log/tx-manager:/log/tx-manager
      - ./log/tx-manager/skywalking:/agent/logs
      - ./agent/agent.config:/agent/config/agent.config
    env_file: .env
    ports:
      - "8501:8501"
  server-system:
    image: 192.168.33.10:3000/cloud/server-system:latest
    container_name: server-system
    networks:
      - web_net
    environment:
      JAVA_TOOL_OPTIONS: "${SERVER_SYSTEM_JAVA_OPS}"
    volumes:
      - ./log/server-system:/log/server-system
      - ./.txlcn:/.txlcn
      - ./log/server-system/skywalking:/agent/logs
      - ./agent/agent.config:/agent/config/agent.config
    env_file: .env
    depends_on:
      - tx-manager
  nginx:
    image: nginx:1.21.3
    container_name: nginx-cloud
    networks:
      - web_net
    environment:
      # 设置时区
      TZ: "Asia/Shanghai"
    privileged: true
    user: root
    ports:
      - "9527:80"
    volumes:
      - ./web:/var/cloud/web
      - ./nginx/:/etc/nginx/
networks:
  web_net:
    external:
      name: cloud_net