version: '3'

services:
  server-system:
    image: ${CLOUD_DEPOSITORY_URL}/server-system:${CLOUD_DEPOSITORY_TAG}
    container_name: server-system
    network_mode: host
    environment:
      JAVA_TOOL_OPTIONS: "${SERVER_SYSTEM_JAVA_OPS}"
    volumes:
      - ./log/server-system:/log/server-system
      - ./.txlcn:/.txlcn
      - ./log/server-system/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    env_file: .env