version: '3'

services:
  # 生产可以不用部署
  server-generator:
    image: ${CLOUD_DEPOSITORY_URL}/server-generator:${CLOUD_DEPOSITORY_TAG}
    container_name: server-generator
    network_mode: host
    environment:
      JAVA_TOOL_OPTIONS: "${SERVER_GENERATOR_JAVA_OPS}"
    volumes:
      - ./log/server-generator:/log/server-generator
      - ./.txlcn:/.txlcn
      - ./log/server-generator/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    env_file: .env