version: '3'

services:
  tx-manager:
    image: ${CLOUD_DEPOSITORY_URL}/tx-manager:${CLOUD_DEPOSITORY_TAG}
    container_name: tx-manager
    network_mode: host
    environment:
      JAVA_TOOL_OPTIONS: "${TX_MANAGER_JAVA_OPS}"
    volumes:
      - ./log/tx-manager:/log/tx-manager
      - ./log/tx-manager/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    env_file: .env