version: '3'

services:
  knife4j:
    image: ${CLOUD_DEPOSITORY_URL}/knife4j:${CLOUD_DEPOSITORY_TAG}
    container_name: knife4j
    network_mode: host
    environment:
      JAVA_TOOL_OPTIONS: "${SERVER_KNIFE4J_JAVA_OPS}"
    volumes:
      - ./log/knife4j:/log/knife4j
    env_file: .env