version: '3'

services:
  auth:
    image: ${CLOUD_DEPOSITORY_URL}/auth:${CLOUD_DEPOSITORY_TAG}
    container_name: auth
    network_mode: host
    environment:
      JAVA_TOOL_OPTIONS: "${AUTH_JAVA_OPS}"
    volumes:
      - ./log/auth:/log/auth
      - ./log/auth/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    env_file: .env