version: '3'

services:
  server-minio:
    image: ${CLOUD_DEPOSITORY_URL}/server-minio:${CLOUD_DEPOSITORY_TAG}
    container_name: server-minio
    network_mode: host
    environment:
      JAVA_TOOL_OPTIONS: "${SERVER_MINIO_JAVA_OPS}"
    volumes:
      - ./log/server-minio:/log/server-minio
      - ./.txlcn:/.txlcn
      - ./log/server-minio/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    env_file: .env