version: '3'

services:
  server-dict:
    image: ${CLOUD_DEPOSITORY_URL}/server-dict:${CLOUD_DEPOSITORY_TAG}
    container_name: server-dict
    network_mode: host
    environment:
      JAVA_TOOL_OPTIONS: "${SERVER_DICT_JAVA_OPS}"
    volumes:
      - ./log/server-dict:/log/server-dict
    env_file: .env