version: "2"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos-standalone-mysql
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    env_file: .env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    #    depends_on:
    #      - mysql
    restart: on-failure
#  mysql:
#    container_name: mysql
#    image: nacos/nacos-mysql:5.7
#    env_file:
#      - ../env/mysql.env
#    volumes:
#      - ./mysql:/var/lib/mysql
#    ports:
#      - "3306:3306"
#  prometheus:
#    container_name: prometheus
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    depends_on:
#      - nacos
#    restart: on-failure
#  grafana:
#    container_name: grafana
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    restart: on-failure

