server:
  port: ${PORT_AUTH:8101}

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    dynamic:
      p6spy: ${LOG_SQL_ENABLED:true}
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
      primary: primary
      datasource:
        primary:
          driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
          url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/${DB_NAME_SYSTEM:cloud_system}?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai}
          username: ${DATASOURCE_USERNAME:root}
          password: ${DATASOURCE_PASSWORD:root}

mybatis-plus:
  type-aliases-package: com.zclcs.common.core.entity.system
  mapper-locations: classpath:com/zclcs/auth/mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

justauth:
  enabled: true
  type:
    github:
      client-id:
      client-secret:
      redirect-uri:
    gitee:
      client-id:
      client-secret:
      redirect-uri:
    tencent_cloud:
      client-id:
      client-secret:
      redirect-uri:
    dingtalk:
      client-id:
      client-secret:
      redirect-uri:
    qq:
      client-id:
      client-secret:
      redirect-uri:
    microsoft:
      client-id:
      client-secret:
      redirect-uri:
  cache:
    type: redis
    prefix: 'MY::CLOUD::SOCIAL::STATE::'
    timeout: 1h

my:
  frontUrl: 'http://localhost:9527'
  doc:
    enable: true
    title: ${spring.application.name}文档
    description: ${my.doc.title}
    name: zclcs
    email: 2371219112@qq.com
    url: https://github.com/zclcs
    version: 2.2-RELEASE

  cloud:
    security:
      enable: true
      only-fetch-by-gateway: false
      anon-uris: /captcha,/social/**,/v2/api-docs,/v2/api-docs-ext,/login,/resource/**

  lettuce:
    redis:
      cache-prefix: ${my.redis-cache.auth-prefix}

  log:
    enable-log-for-controller: ${LOG_CONTROLLER_PARAMS:false}