version: '3'

services:
  auth:
    image: ${CLOUD_DEPOSITORY_IP_PORT}${CLOUD_DEPOSITORY_URL}/auth:${CLOUD_DEPOSITORY_TAG}
    container_name: ${NACOS_NAMESPACE}_auth
    network_mode: host
    command: sh -c "java ${JAVA_OPS_PREFIX} ${AUTH_JAVA_OPS} ${JAVA_OPS_SUFFIX} -cp /app/resources:/app/classes:/app/libs/* ${AUTH_MAIN_CLASS}"
    volumes:
      - ./log/auth:/log/auth
      - ./log/auth/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS ${NACOS_HOST}:${PORT_AUTH} || exit 1" ]
      interval: ${DOCKER_HEALTHCHECK_INTERVAL}
      timeout: ${DOCKER_HEALTHCHECK_TIMEOUT}
      retries: ${DOCKER_HEALTHCHECK_RETRIES}
    env_file: .env