version: '3'

services:
  seata:
    image: ${CLOUD_DEPOSITORY_IP_PORT}/library/seata:1.4.2
    container_name: ${NACOS_NAMESPACE}_seata
    network_mode: host
    environment:
      # 指定seata服务启动端口
      - SEATA_PORT=${SEATA_PORT}
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      - SEATA_IP=${NACOS_DISCOVERY_IP}
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      # 因为registry.conf中是nacos配置中心，只需要把registry.conf放到./seata/config文件夹中
      - ./seata/config:/root/seata-config
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS ${NACOS_HOST}:${SEATA_PORT} || exit 1" ]
      interval: ${DOCKER_HEALTHCHECK_INTERVAL}
      timeout: ${DOCKER_HEALTHCHECK_TIMEOUT}
      retries: ${DOCKER_HEALTHCHECK_RETRIES}
    env_file: .env