DROP DATABASE `cloud_system`;
DROP DATABASE `cloud_generator`;
DROP DATABASE `cloud_test`;
DROP DATABASE `cloud_minio`;
DROP DATABASE `cloud_dict`;
DROP DATABASE `third_part_nacos`;
DROP DATABASE `third_part_seata`;
CREATE DATABASE IF NOT EXISTS `cloud_system` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
CREATE DATABASE IF NOT EXISTS `cloud_generator` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
CREATE DATABASE IF NOT EXISTS `cloud_test` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
CREATE DATABASE IF NOT EXISTS `cloud_minio` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
CREATE DATABASE IF NOT EXISTS `cloud_dict` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
CREATE DATABASE IF NOT EXISTS `third_part_nacos` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
CREATE DATABASE IF NOT EXISTS `third_part_seata` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
CREATE USER 'canal'@'%' IDENTIFIED BY 'canal';
GRANT SHOW VIEW, SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
FLUSH PRIVILEGES;