server:
  port: ${tx-manager-port:8501}
spring:
  boot:
    admin:
      client:
        url: http://${admin-host:127.0.0.1}:${admin-port:8401}
        username: ${admin-security-username:zclcs}
        password: ${admin-security-password:123456}
        instance:
          prefer-ip: true

  datasource:
    driver-class-name: ${datasource-driver:com.mysql.cj.jdbc.Driver}
    url: jdbc:${datasource-db-type:mysql}://${datasource-host:127.0.0.1}:${datasource-port:3306}/${tx-manager-db-name:cloud_tx_manager}?${datasource-param:useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai}
    username: ${datasource-username:root}
    password: ${datasource-password:root}

  redis:
    database: ${tx-manager-redis-database:2}
    host: ${redis-host:127.0.0.1}
    port: ${redis-port:6379}
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

tx-lcn:
  manager:
    host: ${manager-host:0.0.0.0}
    # TM监听Socket端口.
    port: ${manager-port:8888}
    # TM控制台密码
    admin-key: ${manager-admin-key:123456}
  logger:
    # 开启日志记录
    enabled: ${logger-enabled:true}
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}