server:
  port: ${PORT_TX_MANAGER:8501}

spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/${DB_NAME_TX_MANAGER:cloud_tx_manager}?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}

  redis:
    database: ${REDIS_TX_MANAGER_DATABASE:2}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

my:
  log:
    enable-log-for-controller: ${LOG_CONTROLLER_PARAMS:false}

tx-lcn:
  manager:
    host: ${TX_MANAGER_PORT:0.0.0.0}
    # TM监听Socket端口.
    port: ${TX_CLIENT_MANAGER_PORT:8888}
    # TM控制台密码
    admin-key: ${TX_MANAGER_ADMIN_KEY:123456}
  logger:
    # 开启日志记录
    enabled: ${TX_LOGGER_ENABLED:true}
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}