version: '3'

services:
  # 生产可以不用部署
  server-generator:
    image: ${CLOUD_DEPOSITORY_URL}/server-generator:${CLOUD_DEPOSITORY_TAG}
    container_name: server-generator
    network_mode: host
    command: sh -c "/wait && java ${SERVER_GENERATOR_JAVA_OPS} -cp /app/resources:/app/classes:/app/libs/* ${SERVER_GENERATOR_MAIN_CLASS}"
    environment:
      WAIT_HOSTS: ${NACOS_HOST}:${PORT_TX_MANAGER}, ${NACOS_HOST}:${PORT_SERVER_SYSTEM}
      WAIT_SLEEP_INTERVAL: ${DOCKER_WAIT_SLEEP_INTERVAL}
      WAIT_HOST_CONNECT_TIMEOUT: ${DOCKER_WAIT_HOST_CONNECT_TIMEOUT}
      WAIT_TIMEOUT: ${DOCKER_WAIT_TIMEOUT}
    volumes:
      - ./log/server-generator:/log/server-generator
      - ./.txlcn:/.txlcn
      - ./log/server-generator/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    env_file: .env