version: '3'

services:
  # 生产可以不用部署
  server-test:
    image: ${CLOUD_DEPOSITORY_URL}/server-test:${CLOUD_DEPOSITORY_TAG}
    container_name: server-test
    network_mode: host
    command: sh -c "/wait && java ${SERVER_TEST_JAVA_OPS} -cp /app/resources:/app/classes:/app/libs/* ${SERVER_TEST_MAIN_CLASS}"
    environment:
      WAIT_HOSTS: ${NACOS_HOST}:${PORT_TX_MANAGER}
      WAIT_SLEEP_INTERVAL: ${DOCKER_WAIT_SLEEP_INTERVAL}
      WAIT_HOST_CONNECT_TIMEOUT: ${DOCKER_WAIT_HOST_CONNECT_TIMEOUT}
      WAIT_TIMEOUT: ${DOCKER_WAIT_TIMEOUT}
    volumes:
      - ./log/server-test:/log/server-test
      - ./.txlcn:/.txlcn
      - ./log/server-test/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://${NACOS_HOST}:${PORT_SERVER_TEST}' || exit 1" ]
      interval: ${DOCKER_HEALTHCHECK_INTERVAL}
      timeout: ${DOCKER_HEALTHCHECK_TIMEOUT}
      retries: ${PORT_SERVER_MINIO}
    env_file: .env