version: '3'

services:
  tx-manager:
    image: ${CLOUD_DEPOSITORY_URL}/tx-manager:${CLOUD_DEPOSITORY_TAG}
    container_name: tx-manager
    network_mode: host
    command: sh -c "java ${TX_MANAGER_JAVA_OPS} -cp /app/resources:/app/classes:/app/libs/* ${TXMANAGER_MAIN_CLASS}"
    volumes:
      - ./log/tx-manager:/log/tx-manager
      - ./log/tx-manager/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    env_file: .env